### PR TITLE
appendBitmapText error handling

### PR DESCRIPTION
**Pull request by matthewparavati**
adds some error handling for the appendBitmapText block
 - adds the promise as an argument appendCommands and rejects it if an error is caught
 - main reason for adding this was sc-14192
   - Unsure of exact reason for error at the moment, this will at least help avoid a crash

### CODE REVIEW

**Review by oliveirasWell — APPROVED** [review]
On my end, I was able to print without the warning, so I guess it's okay

btw, for a little help testing, this could help to avoid building the package locally, so just need to add this line to the package.json

"@popmenu/star-print": "https://github.com/popmenu/react-native-star-prnt.git#matthewparavati/nullPointerException-try-catch",

**Comment by matthewparavati** [comment]
> On my end, I was able to print without the warning, so I guess it's okay
> 
> btw, for a little help testing, this could help to avoid building the package locally, so just need to add this line to the package.json
> 
> "@popmenu/star-print": "https://github.com/popmenu/react-native-star-prnt.git#matthewparavati/nullPointerException-try-catch",

Yeah, should've added that. And apparently all you need is `"@popmenu/star-print": "popmenu/react-native-star-prnt#[branch name]"` and it will pull from the correct branch

**Comment by bp1295** [comment]
Approving for now, but still need to test

**Comment by bp1295** [comment]
Tested, this is good to go

**Review by bp1295 — APPROVED** [review]

**Pull request merged**
